name: build container (bootc)
run-name: building container (bootc)
on:
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run podman build - steamlink (bootc)
        run: |
          podman build -t ghcr.io/gbraad-gaming/steamlink-bootc:latest \
            --build-arg=BASE_IMAGE="ghcr.io/gbraad-devenv/fedora/rdesktop-bootc" \
            --build-arg=BASE_VERSION=41 \
            -f Containerfile .
      - name: Push image to ghcr.io - steamlink (bootc)
        run: |
          podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/gbraad-gaming/steamlink-bootc:latest